project_name: oneget

env:
  - GO111MODULE=on
#  - GOPROXY=https://goproxy.io
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
dist: dist

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^skip:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
      - 'v8platform/{{.ProjectName}}:{{ .Tag }}'
      - 'v8platform/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}'
      - 'v8platform/{{.ProjectName}}:latest'
      - 'ghcr.io/v8platform/{{.ProjectName}}:{{ .Tag }}'
      - 'ghcr.io/v8platform/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/v8platform/{{.ProjectName}}:latest'
    dockerfile: Dockerfile
    ids:
      - oneget
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=com.github.actions.description=Console app for download packages from releases.1c.ru"
      - "--label=com.github.actions.icon=terminal"
      - "--label=com.github.actions.color=blue"
      - "--label=repository=https://github.com/v8platform/oneget"
      - "--label=homepage=https://github.com/v8platform/oneget"
      - "--label=maintainer=Ruslan Zhdanov"
  - image_templates:
      - 'demoncat/{{.ProjectName}}:{{ .Tag }}'
      - 'demoncat/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}'
      - 'demoncat/{{.ProjectName}}:latest'
      - 'ghcr.io/v8platform/{{.ProjectName}}:{{ .Tag }}'
      - 'ghcr.io/v8platform/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/v8platform/{{.ProjectName}}:latest'
    dockerfile: Dockerfile_s
    ids:
      - oneget
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=com.github.actions.description=Console app for download packages from releases.1c.ru"
      - "--label=com.github.actions.icon=terminal"
      - "--label=com.github.actions.color=blue"
      - "--label=repository=https://github.com/v8platform/oneget"
      - "--label=homepage=https://github.com/v8platform/oneget"
      - "--label=maintainer=Ruslan Zhdanov"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

